//
//  BranchConfig.h
//  adobe-branch-example
//
//  Created by Aaron Lopez on 9/19/18.
//  Copyright © 2018 Aaron Lopez. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <ACPCore_iOS/ACPCore_iOS.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT NSString* const BRANCH_KEY_CONFIG;
FOUNDATION_EXPORT NSString* const BRANCH_EVENT_TYPE;
FOUNDATION_EXPORT NSString* const BRANCH_EVENT_TYPE_INIT;
FOUNDATION_EXPORT NSString* const BRANCH_EVENT_TYPE_DEEP_LINK;
FOUNDATION_EXPORT NSString* const BRANCH_EVENT_TYPE_SHARE_SHEET;
FOUNDATION_EXPORT NSString* const BRANCH_EVENT_TYPE_CONSTANT;
FOUNDATION_EXPORT NSString* const BRANCH_EVENT_SOURCE_STANDARD;
FOUNDATION_EXPORT NSString* const BRANCH_EVENT_SOURCE_CUSTOM;

NS_ASSUME_NONNULL_END
