platform :ios, '12.0'

target 'AdobeBranchExample' do
  use_frameworks!

  pod 'BranchSDK'
  
  pod 'AEPCore', '~> 5.0'
  pod 'AEPEdge'
  pod 'AEPEdgeIdentity'
  pod 'AEPLifecycle'
  pod 'AEPServices'


  pod 'AdobeBranchExtension', :path => '../../'
end
