#!/bin/bash
set -euo pipefail

function full_path_of_directory() {
    local directory_name
    directory_name="$1"
    current_directory=$(pwd)
    while [[ "$(basename "$current_directory")" != "$directory_name" && ${#current_directory} -gt 1 ]]
    do
        current_directory=$(dirname "$current_directory")
    done
    if (( ${#current_directory} <= 1 ))
    then
        echo ">>> Error: Path of '$1' not found." 1>&2
        kill -9 -- $$
        exit 1
    fi
    echo "$current_directory"
}

project_directory="$(full_path_of_directory AdobeBranchExtension-iOS)"
cd "$project_directory"

# Remove `--allow-warnings` when Adobe fixes their warnings.
pod lib lint --allow-warnings

version="$(./scripts/version)"
echo '>>> The build is successful so far.' 1>&2
if ! ./scripts/askYN "Commit and deploy release version ${version}?"; then
    echo ">>> Nothing deployed." 1>&2
    exit 1
fi

echo ">>> Publishing version $version to 'master'..." 1>&2

git add --all
git commit --allow-empty -m "Release ${version}."
git tag v"${version}"
git push --tags origin master

pod spec lint
pod trunk push AdobeBranchExtension.podspec
