# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'adobe-branch-example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for adobe-branch-example
  pod 'Branch'
  pod 'ACPCoreBeta', '1.0.1beta'
end
